version: '3.8'

services:
  mongo:
    image: 'mongo'
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - service_networks

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8010
    volumes:
      - .:/app/
    ports:
      - ${SERVER_PORT}:8010
    depends_on:
      - 'mongo'
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      PYTHONPATH: /app
    env_file:
      - ./.env
    networks:
      - service_networks

networks:
  service_networks:
    driver: bridge

volumes:
  mongo_data: